In [8]:
import numpy as np

NORMALIZATION PROBLEM

In [9]:
X = np.random.rand(5, 5)
print("Original X:\n", X)

Original X:
 [[0.28623683 0.76329285 0.18948959 0.88330832 0.81474404]
 [0.70718219 0.56776776 0.57400492 0.9263899  0.1306332 ]
 [0.79163687 0.16435679 0.90506778 0.66211793 0.31257525]
 [0.30093598 0.41490301 0.22200656 0.20683719 0.73877744]
 [0.94289105 0.64584505 0.19066772 0.52054538 0.3667299 ]]


In [14]:
mean_X = X.mean()
std_X = X.std()

X_normalized = (X - mean_X) / std_X
print("Normalized X:\n", X_normalized)

Normalized X:
 [[-0.89810646  0.86562436 -1.25579211  1.30933533  1.05584533]
 [ 0.65817683  0.14274569  0.16580516  1.46861286 -1.47339094]
 [ 0.97041545 -1.34871098  1.38978256  0.49156906 -0.80073033]
 [-0.84376205 -0.42241284 -1.13557316 -1.19165605  0.77498809]
 [ 1.5296195   0.43140637 -1.25143645 -0.03184087 -0.60051436]]


In [ ]:
np.save("X_normalized.npy", X_normalized)

DIVISIBLE BY 3 PROBLEM

In [17]:
A = np.arange(1, 101) **2
A = A.reshape(10,10)
print("10x10ndarray of quares:\n", A)

10x10ndarray of quares:
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [19]:
div_by_3 = A[A % 3 == 0 ]
print("Elements divisible by 3:\n", div_by_3)

Elements divisible by 3:
 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [20]:
np.save("div_by_3.npy", div_by_3)